### ISSUE TITLE
Does not run with Deno 0.34?

### ISSUE THREAD

**Issue by gitblit** [kryz81/deno-api-example#3]
I wanted to play around with your nicely crafted example but I got a little stuck.

Am I running this the wrong way?
Is there an expected configuration to loosen the TypeScript checks?
Does this example expect an older version of Deno? (or TS?)

Sorry for so many questions.  JS/TS is out of my comfort zone.

```
F:\git\deno-api-example [master ≡]> deno --version
deno 0.34.0
v8 8.1.108
typescript 3.7.2

F:\git\deno-api-example [master ≡]> deno run .\index.ts
Compile file:///F:/git/deno-api-example/index.ts
error TS7031: Binding element 'request' implicitly has an 'any' type.

► file:///F:/git/deno-api-example/handlers/createUser.ts:3:25

3 export default async ({ request, response }) => {
                          ~~~~~~~

error TS7031: Binding element 'response' implicitly has an 'any' type.

► file:///F:/git/deno-api-example/handlers/createUser.ts:3:34

3 export default async ({ request, response }) => {
                                   ~~~~~~~~

error TS7031: Binding element 'params' implicitly has an 'any' type.

► file:///F:/git/deno-api-example/handlers/deleteUser.ts:3:25

3 export default async ({ params, response }) => {
```

Plus several other examples of the same issue.

**Comment by kryz81** [comment]
Hi, 
thank you for letting me now.

I fixed the problem and it works with 0.34 now.
